openapi: 3.0.0
info:
  title: Traval App API
  description: Optional multiline or single-line description in [CommonMark](http://commonmark.org/help/) or HTML.
  version: 0.1.9

servers:
  - url: http://localhost:3000
    description: server localhost 3000

paths:
  /register:
    get:
      tags:
       - Register
      summary: Returns a list of register.
      description: Optional extended description in CommonMark or HTML.
      responses:
        "200": # status code
          description: A JSON array of user names
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string