openapi: 3.0.0
info:
  title: Traval App API
  description: API for managing user profiles.
  version: 0.1.9

servers:
  - url: http://localhost:3000
    description: Localhost server on port 3000

paths:
  /profile:
    get:
      tags: [profile]
      summary: Returns a list of profiles.
      responses:
        "200":
          description: A JSON array of profiles
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    account_id:
                      format: int64
                    account_email:
                      type: string
                    account_name:
                      type: string
                    account_gender:
                      type: string
                    account_birthday:
                      type: string
                      format: date
                    account_picture:
                      type: string
                    account_telephone:
                      type: string
                    latitude:
                      type: number
                      format: float
                    longitude:
                      type: number
                      format: float
                    created_at:
                      type: string
                      format: date-time
                    updated_at:
                      type: string
                      format: date-time

    post:
      summary: Creates a new profile.
      tags: [profile]
      requestBody:
        required: true 
        content:
          application/json:
            schema:
              type: object
              required:
                - account_email
                - account_password
                - account_name
              properties:
                account_email:
                  type: string
                account_password:
                  type: string  
                account_name:
                  type: string
                account_gender:
                  type: string
                account_birthday:
                  type: string
                  format: date  
                account_picture:
                  type: string   
                account_telephone:
                  type: string
                latitude:
                  type: number
                  format: float                  
                longitude:
                  type: number
                  format: float     
      responses: 
        '201':
          description: User successfully created

  /profile/{id}:
    get:
      summary: Returns a profile by ID.
      tags: [profile]
      parameters:
        - name: id
          in: path
          required: true
          description: User ID
          schema:
            type: integer
            format: int64
            minimum: 1
      responses: 
        '200':
          description: Profile found
          content:
            application/json:
              schema:
                type: object
                properties:
                  account_id:
                    type: integer
                    format: int64
                  account_email:
                    type: string
                  account_name:
                    type: string
                  account_gender:
                    type: string
                  account_birthday:
                    type: string
                    format: date
                  account_picture:
                    type: string
                  account_telephone:
                    type: string
                  latitude:
                    type: number
                    format: float
                  longitude:
                    type: number
                    format: float
                  created_at:
                    type: string
                    format: date-time
                  updated_at:
                    type: string
                    format: date-time
        '404':
          description: Profile not found

put:
  summary: Updates a profile.
  tags: [profile]
  parameters:
    - name: id
      in: path
      required: true
      description: User ID
      schema:
        type: integer
        format: int64
  requestBody:
    required: true 
    content:
      application/json:
        schema:
          type: object
          properties:
            account_email:
              type: string
            account_password:
              type: string  
            account_name:
              type: string
            account_gender:
              type: string
            account_birthday:
              type: string
              format: date  
            account_picture:
              type: string   
            account_telephone:
              type: string
            latitude:
              type: number
              format: float                  
            longitude:
              type: number
              format: float     
  responses: 
    '200':
      description: Profile updated successfully
    '404':
      description: Profile not found
    '500':
      description: Internal server error
